---
- name: Update packadges "{{ inventory_hostname }}"
  apt:
    name: nginx
    state: "latest"
    update_cache: yes
  tags:
    - step_1
    
- name: Set config
  template:
    src: roles/balancer/vars/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart
  tags:
    - step_2

- name: New site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart
  tags:
    - step_3
