---
- name: Create CA key
  openssl_privatekey:
    path: ca_cert/ca.key
    state: present

- name: Create CSR for CA cert
  openssl_csr:
    path: ca_cert/ca-certificate.pem
    privatekey_path: ca_cert/ca.key
    common_name: Ansible CA
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
    key_usage_critical: true
    state: present
  register: ca_csr

- name: Create CA cert
  openssl_certificate:
    path: ca_cert/ca-certificate.crt
    csr_path: ca_cert/ca-certificate.pem
    privatekey_path: ca_cert/ca.key
    provider: selfsigned
    state: present

- name: Create CSR for server cert
  openssl_csr:
    path: ca_cert/srv-certificate.pem
    privatekey_path: ca_cert/ca.key
    common_name: nginx-1.local
    email_address: my.email@example.com
    organization_name: Private Person
    organizational_unit_name: Alter ego dept
    locality_name: Korolyov
    country_name: RU
    state: present

- name: Create srv cert
  openssl_certificate:
    path: ca_cert/srv-certificate.crt
    csr_path: ca_cert/srv-certificate.pem
    privatekey_path: ca_cert/ca.key
    provider: selfsigned
    state: present

- name: Create CSR for client1 cert
  openssl_csr:
    path: ca_cert/client1-certificate.pem
    privatekey_path: ca_cert/ca.key
    common_name: client1
    email_address: client1@example.com
    organization_name: Client1
    organizational_unit_name: Client1
    state: present

- name: Create client1 cert
  openssl_certificate:
    path: ca_cert/client1-certificate.crt
    csr_path: ca_cert/client1-certificate.pem
    privatekey_path: ca_cert/ca.key
    provider: selfsigned
    state: present

- name: Create CSR for client2 cert
  openssl_csr:
    path: ca_cert/client2-certificate.pem
    privatekey_path: ca_cert/ca.key
    common_name: client2
    email_address: client2@example.com
    organization_name: Client2
    organizational_unit_name: Client2
    state: present

- name: Create client2 cert
  openssl_certificate:
    path: ca_cert/client2-certificate.crt
    csr_path: ca_cert/client2-certificate.pem
    privatekey_path: ca_cert/ca.key
    provider: selfsigned
    state: present