---
- name: Create CA key
  openssl_privatekey:
    path: ca_cert/ca.key
  register: ca_key


- name: Create CSR for CA cert
  openssl_csr:
    path: ca_cert/ca.csr
    privatekey_path: "{{ ca_key.filename }}"
    common_name: "myCA"
  register: ca_csr

- name: Create CA cert
  openssl_certificate:
    path: ca_cert/ca.crt
    csr_path: "{{ ca_csr.filename }}"
    privatekey_path: "{{ ca_key.filename }}"
    provider: selfsigned
  register: ca_crt

- name: Create srv key
  openssl_privatekey:
    path: ca_cert/server.key
  register: server_key

- name: Create CSR for server cert
  openssl_csr:
    path: ca_cert/server.csr
    privatekey_path: "{{ server_key.filename }}"
    common_name: nginx-1.local
    email_address: my.email@example.com
    organization_name: Private Person
    organizational_unit_name: Alter ego dept
    locality_name: Korolyov
    country_name: RU
    subject_alt_name:
      - "DNS:nginx-1.local"
      - "IP:127.0.0.1"
      - "IP:192.168.56.101"
  register: server_csr

- name: Create srv cert and sign
  openssl_certificate:
    path: ca_cert/server.crt
    csr_path: "{{ server_csr.filename }}"
    provider: ownca
    ownca_path: "{{ ca_crt.filename }}"
    ownca_privatekey_path: "{{ ca_key.filename }}"
  register: server_crt