---
- name: Create CA key
  openssl_privatekey:
    path: ca_cert/ca.key
  run_once: true

- name: Create CSR for CA cert
  openssl_csr:
    path: ca_cert/ca-certificate.pem
    privatekey_path: ca_cert/ca.key
    common_name: Ansible CA
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
    key_usage_critical: true
  run_once: true

- name: Create CA cert
  openssl_certificate:
    path: ca_cert/ca-certificate.crt
    csr_path: ca_cert/ca-certificate.pem
    privatekey_path: ca_cert/ca.key
    provider: selfsigned
    state: present

- name: Create srv key
  openssl_privatekey:
    path: ca_cert/srv-certificate.key
  run_once: true

- name: Create CSR for server cert
  openssl_csr:
    path: ca_cert/srv-certificate.pem
    privatekey_path: ca_cert/srv-certificate.key
    common_name: nginx-1.local
    email_address: my.email@example.com
    organization_name: Private Person
    organizational_unit_name: Alter ego dept
    locality_name: Korolyov
    country_name: RU
    subject_alt_name:
      - "DNS:nginx-1.local"
      - "IP:127.0.0.1"
  run_once: true

- name: Create srv cert
  openssl_certificate:
    path: ca_cert/srv-certificate.crt
    csr_path: ca_cert/srv-certificate.pem
    privatekey_path: ca_cert/ca.key
    provider: selfsigned
  run_once: true