- name: install helm
  unarchive:
    src: https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
    - --strip-components=1
    - linux-amd64/helm
    creates: /usr/local/bin/helm

#- name: add hashicorp helm repo
#  community.kubernetes.helm_repository:
#    name: hashicorp
#    repo_url: "https://helm.releases.hashicorp.com"

- name: add bitnami helm repo
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: add nginx-ingress helm repo
  community.kubernetes.helm_repository:
    name: nginx-stable
    repo_url: "https://helm.nginx.com/stable"

- name: add nginx-ingress helm repo
  community.kubernetes.helm_repository:
    name: jenkins
    repo_url: "https://charts.jenkins.io"

- name: Create a k8s namespace
  community.kubernetes.k8s:
    name: vault
    api_version: v1
    kind: Namespace
    state: present

- name: Create a k8s namespace
  community.kubernetes.k8s:
    name: jenkins
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy etcd-vault
  community.kubernetes.helm:
    name: etcd-vault
    release_namespace: vault
    chart_ref: bitnami/etcd
    values: "{{ lookup('template', 'values-etcd.yaml') | from_yaml }}"

- name: Deploy ingress
  community.kubernetes.helm:
    name: nginx-ingress
    release_namespace: ingress
    create_namespace: yes
    chart_ref: nginx-stable/nginx-ingress
    values: "{{ lookup('template', 'values-ingress.yaml') | from_yaml }}"

- name: Deploy vault
  community.kubernetes.helm:
    name: vault
    release_namespace: vault
#    chart_ref: hashicorp/vault
    chart_ref: "https://s828sas.storage.yandex.net/rdisk/883de96d08f756fcde70ac049d136571f25c5fedbe62603ebe9ff0b3d8b4cea5/63334044/8x_48cuVBKIlBhsWhwQfPl3sGC0cXlPOlcb7y36b52LtK7nrMJ8cRy_-0O_0QLAxf0b9yR4hZhN5EMb2XjJD0w==?uid=0&filename=vault.tgz&disposition=attachment&hash=6garVG2CUaRIVfW51GxGn1hIe0qljY3pytfK1JLC2pGLrK2JFcoEChu99UF8FjeOq/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=application%2Fx-gzip&owner_uid=1645876&fsize=73273660&hid=dbb9c7854ed540b8c46dbea81bd31d1b&media_type=compressed&tknv=v2&rtoken=oU3iVBJgPOxz&force_default=no&ycrid=na-1b635d7298953c017ec0ab7c419b5747-downloader1h&ts=5e9acc75d9900&s=73039af341cc148d88fdfc753f343758f1b2734825da1b4d922032640bf9d047&pb=U2FsdGVkX1-Bepiy4wyNb9jBmSMoctlcvTm-JjqBMMwLRIYay9wxluXE2lDT-c18Gu7kKUl68GhGmvNdsw0dMUvtL0Fv5DIdXFnXJkriJss"
#    values: "{{ lookup('template', 'values-vault.yaml') | from_yaml }}"

- name: Deploy jenkins
  community.kubernetes.helm:
    name: jenkins
    release_namespace: jenkins
    chart_ref: jenkins/jenkins
    values: "{{ lookup('template', 'values-jenkins.yaml') | from_yaml }}"

